server:
  port: 8080
spring:
  config:
    import:
      - classpath:datapulse-core.yml
      - classpath:datapulse-marketplaces.yml
      - classpath:datapulse-etl.yml

logging:
  level:
    liquibase: INFO
